export const SET_AUTHED_USER = 'SET_AUTHED_USER'
export const CLEAR_AUTHED_USER = 'CLEAR_AUTHED_USER'

export const RECEIVE_USERS = 'RECEIVE_USERS'
export const USER_ADD_QUESTION = 'USER_ADD_QUESTION'
export const USER_ANSWER_QUESTION = 'USER_ANSWER_QUESTION'

export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS'
export const ADD_QUESTION = 'ADD_QUESTION'
export const ANSWER_QUESTION = 'ANSWER_QUESTION'

